language: php
sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    # 'php: nightly' is PHP 8.0
    - php: 7.4snapshot
    - php: 7.3
      env: SYMFONY="3.4.*"
        ACTION="update"
    - php: 7.3
      env: SYMFONY="4.4.*"
        ACTION="update"
    - php: 7.3
      env: SYMFONY="5.0.*"
        ACTION="update"
  allow_failures:
    - php: 7.4snapshot
    - php: 7.3
      env: SYMFONY="3.4.*"
        ACTION="update"
    - php: 7.3
      env: SYMFONY="4.4.*"
        ACTION="update"
    - php: 7.3
      env: SYMFONY="5.0.*"
        ACTION="update"

before_install:
  - composer self-update
  - composer clear-cache

install:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable

script:
  - ./vendor/bin/phpunit
